services:
  backend:
    build: .
    container_name: backend
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: my_db
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_CONNECTION: mysql
    ports:
      - 80:80